class ApplicationController < ActionController::API
  include ActionController::Cookies

  def login
    user_to_find_to_login=User.find_by(username: params[:username])


  if user_to_find_to_login #now we want to verify their password

    if user_to_find_to_login.authenticate(params[:password])
      render json: user_to_find_to_login

    else 
      render json: {error: "**Check Your Password, Homie**"}
    end

    else
      render json: {error: "Username OR Password Don't Match "}
    end

  end

end
    # render json: {error: "No username matches, homie"}

  # skip_before_action :verify_authenticity_token
  # rails has rules when communicating with routes. this rule is a token. this token is generated by the system by our secret key value and it makes sure the user is the real user. in an api we need to skip that process and thats what this does
 




  # skip_before_action :verify_authenticity_token
  # rails has rules when communicating with routes. this rule is a token. this token is generated by the system by our secret key value and it makes sure the user is the real user. in an api we need to skip that process and thats what this does
 
